<?php
/**
 * BuschFunk Templates
 * Catalog > Product > View > Options for Ticket Products
 */

$_product = $this->getProduct();
$_events = $this->getEvents();

$helper = Mage::helper('bufu_tickets');

$firstItemCall = "";
$liItems = array();
$detailItems = array();
$cnt = 0;
foreach($_events as $event) {
    // update status to account for upcoming dates that can only be purchased at the abendkasse
    $event->updateUpcomingStatus();

    // build li item
    $liItem = '<li class="item';
    if ($cnt == 0) $liItem .= ' first';
    if ($cnt % 2 == 0) $liItem .= ' even';
    $liItem .= '" id="bufu_tickets-selectbox-event-'. $event->getId() .'"';
    $spa = ($event->getIsSpecialPriceAvailable() === true) ? "true" : "false";
    $qtyTracking = "null";
    if ($helper->isQuantityTrackingEnabled() && $event->getIsTrackQty()) {
        $qtyTracking = "[{$event->getQtyNormal()}, {$event->getQtySpecial()}]";
    }
    $jsCall = "bufu_tickets_showEvent(". $event->getId() .", ". $event->getIsAvailable() .", '". $event->getPriceNormal($_product) ."', '". $event->getPriceSpecial($_product) ."', ". $spa .", {$qtyTracking})";
    if ($cnt == 0) {
        // add semicolon at the end to js call ...
        $firstItemCall = $jsCall . ";";
    }
    $liItem .= ' onclick="return '. $jsCall .'">';
    $liItem .= '<a href="#termin-'. $event->getId() .'" onclick="return '. $jsCall .'">';
    $liItem .= $event->getEventLocalDate() .' '. $event->getEventLocation();
    $liItem .= '</a></li>' . PHP_EOL;

    // build date detail item
    $eventItem = '<div class="item" id="bufu_tickets-selectbox-item-'. $event->getId() .'">';
    $eventItem .= '<a name="termin-'. $event->getId() .'"></a>';
    $eventItem .= '<strong>'. $event->getEventTitle() .'</strong>';
    $eventItem .= '<p>'. $event->getEventLocalDate() .' '. $event->getEventLocation() .'</p>';
    $eventItem .= '<p>Beginn: '. $event->getEventLocalTime() .' Uhr</p>';
    $eventItem .= '<p>Preis: '. $helper->getFormattedPrice($event->getPriceNormal($_product)) .' €';
    if ($event->getIsSpecialPriceAvailable() === true) {
        $eventItem .= ' / erm. '. $helper->getFormattedPrice($event->getPriceSpecial($_product)) .' €</p>';
    }
    $eventItem .= '</p>';
    switch ((int) $event->getIsAvailable()) {
        case Bufu_Tickets_Helper_Data::STATUS_AVAILABLE:
            $eventItem .= '<p class="status green">Ausreichend Karten verfügbar</p>';
            break;
        case Bufu_Tickets_Helper_Data::STATUS_SOMELEFT:
            $eventItem .= '<p class="status yellow">Restkarten verfügbar</p>';
            break;
        case Bufu_Tickets_Helper_Data::STATUS_REQUEST:
            $eventItem .= '<p class="status yellow">Bitte telefonisch nachfragen</p>';
            break;
        case Bufu_Tickets_Helper_Data::STATUS_SOLDOUT:
            $eventItem .= '<p class="status red">Leider ausverkauft!</p>';
            break;
        case Bufu_Tickets_Helper_Data::STATUS_ABENDKASSE:
            $eventItem .= '<p class="status yellow">Karten nur noch an der Abendkasse erhältlich!</p>';
            break;
    }
    if (strlen($event->getEventDesc()) > 0) {
        $eventItem .= '<p class="desc">'. $event->getEventDesc() .'</p>';
    }
    $eventItem .= '</div>' . PHP_EOL;

    $liItems[] = $liItem;
    $detailItems[] = $eventItem;

    $cnt ++;

}
?>

<a name="termine"></a>
<h2>Terminauswahl</h2>
<div class="bufu_tickets-selectbox clearfix">
    <?php if (count($_events) > 0) : ?>
    <div class="dates">
        <p>Termine</p>
        <ul>
            <?php echo implode($liItems) ?>
        </ul>
    </div>
    <div class="details">
        <?php echo implode($detailItems) ?>

        <?php echo $this->getChildHtml('bufu_tickets.addtocart');?>

    </div>

    <script type="text/javascript">
    // <![CDATA[
    document.observe("dom:loaded", function() {
        bufu_tickets_setProductId(<?php echo $_product->getId() ?>);
        <?php echo $firstItemCall ?>
    });
    // ]]>
    </script>
    <?php else : ?>
    <p class="note-msg" style="margin:1em">Es sind keine Konzerttermine verfügbar.</p>
    <?php endif; ?>
</div>
