<?php
/**
 * BuschFunk Templates
 * Checkout > Review
 */
?>
<p class="hint">
    <?php echo $this->__('Please check that all given information and the listed products are correct before submitting your order.') ?>
</p>

<div id="checkout-review-load" class="default-box">
    <?php echo $this->getChildHtml('info') ?>
</div>

<?php echo $this->getChildHtml('multipartdelivery'); ?>
<?php echo $this->getChildHtml('checkoutNotice'); ?>

<?php echo $this->getChildHtml('agreements') ?>
<div class="content button-set">
    <div class="left">
        <p class="editCart"><?php echo $this->__('Forgot an Item?') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Your Cart') ?></a></p>
        <div id="review-please-wait" style="display:none;" class="opc-please-wait" style="text-align:left">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="" /> &nbsp; <?php echo $this->__('Submitting order information...') ?> &nbsp;
        </div>
    </div>
    <div id="review-buttons-container" class="right">
        <input type="image" src="<?php echo $this->getSkinUrl('images/defaults/gfx_btn_order.png') ?>" onclick="review.save();" value="<?php echo $this->__('Place Order') ?>" />
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    var review = new Review('<?php echo $this->getUrl('checkout/onepage/saveOrder') ?>', '<?php echo $this->getUrl('checkout/onepage/success') ?>', $('checkout-agreements'));
//]]>
</script>
