<?php
/**
 * BuschFunk Template
 * Contact Form
 */

 $telephone = Mage::getStoreConfig("general/imprint/telephone");
 $email = Mage::getStoreConfig("trans_email/ident_general/email");

?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<div class="page-head">
<h2>Kontaktieren Sie uns</h2>
</div>
<p>Sie erreichen uns zu den Bürozeiten unter<br />
  Telefon: <a href="tel:<?php echo $telephone ?>"><?php echo $telephone ?></a>, sowie<br />
  per Email unter <a href="mailto:<?php echo $email ?>"><?php echo $email ?></a>.
</p>
<p>Oder verwenden Sie einfach unser Kontaktformular.</p>

<div class="box sendfriend-form">
 <form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post">
  <?php echo $this->getBlockHtml('formkey') ?>
    <div class="content">
        <div>
            <h4><?php echo Mage::helper('contacts')->__('Contact Information') ?></h4>
            <ul class="form-list">
            <li>
                <div class="text-input left">
                    <label for="name"><?php echo Mage::helper('contacts')->__('Name') ?> <span class="required">*</span></label><br />
                    <input name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserName()) ?>" class="required-entry input-text" type="text" />
                </div>

                <div class="text-input right">
                    <label for="email"><?php echo Mage::helper('contacts')->__('Email') ?> <span class="required">*</span></label><br />
                    <input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserEmail()) ?>" class="required-entry input-text validate-email" type="text" />
                </div>
                <div class="clear"></div>
            </li>
            <li>
                <div class="text-input left">
                    <label for="telephone"><?php echo Mage::helper('contacts')->__('Telephone') ?></label><br />
                    <input name="telephone" id="telephone" title="<?php echo Mage::helper('contacts')->__('Telephone') ?>" value="" class="input-text" type="text" />
                </div>
                <div class="clear"></div>
            </li>
            <li>
                <label for="comment"><?php echo Mage::helper('contacts')->__('Comment') ?> <span class="required">*</span></label><br />
                <textarea name="comment" id="comment" title="<?php echo Mage::helper('contacts')->__('Comment') ?>" class="required-entry text-area"></textarea>
            </li>
            </ul>
        </div>
        <div class="clear"></div>
        <div class="button-set">
            <p class="required right"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
            <a href="#" onclick="contactForm.submit();return false" class="gfx-button">
                <span>
                    <span class="email-go"><?php echo Mage::helper('contacts')->__('Submit') ?></span>
                </span>
            </a>
        </div>
    </div>
</form>
</div>
<script type="text/javascript">
    var contactForm = new VarienForm('contactForm', true);
</script>
