<?php
/**
 * BuschFunk Tenplates
 * Checkout > Cart > Link to checkout
 */
?>
<?php if ($this->isPossibleOnepageCheckout()):?>
<li>
<?php if ($this->isDisabled()):?>
<img src="<?php echo $this->getSkinUrl('images/defaults/gfx_btn_checkout_dis.png');?>" alt="<?php echo Mage::helper('checkout')->__('Proceed to Checkout');?>" title="<?php echo Mage::helper('checkout')->__('Proceed to Checkout not possible!');?>" />
<?php else: ?>
<a href="<?php echo $this->getCheckoutUrl()?>" title="<?php echo Mage::helper('checkout')->__('Proceed to Checkout');?>"><img src="<?php echo $this->getSkinUrl('images/defaults/gfx_btn_checkout.png');?>" alt="<?php echo Mage::helper('checkout')->__('Proceed to Checkout');?>" /></a>
<?php endif?>
</li>
<?php endif?>