<?php
/**
 * BuschFunk Templates
 * > Breadcrumbs
 */
?>
<?php if($crumbs && is_array($crumbs)): ?>
<ul class="breadcrumbs">
    <li class="start"><?php echo $this->__("You're currently on:") ?></li>
    <?php foreach($crumbs as $_crumbName=>$_crumbInfo): ?>
        <li class="<?php echo $_crumbName ?>">
        <?php if($_crumbInfo['link']): ?>
            <a href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->htmlEscape($_crumbInfo['title']) ?>"><?php echo $this->htmlEscape($_crumbInfo['label']) ?></a>
        <?php elseif($_crumbInfo['last']): ?>
            <strong><?php echo $this->htmlEscape($_crumbInfo['label']) ?></strong>
        <?php else: ?>
            <?php echo $this->htmlEscape($_crumbInfo['label']) ?>
        <?php endif; ?>
        </li>
        <?php if(!$_crumbInfo['last']): ?>
        <li class="li-divider">&nbsp;</li>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
