<?php
/**
 * BuschFunk Templates
 * > HTML Page Header
 */
?>

<div class="header-top-container">
    <div class="header-top">
        <h1 id="logo"><a href="<?php echo $this->getUrl('') ?>" title="zur Startseite des Konsum"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
        <p class="welcome">
            <?php /* echo $this->getWelcome()*/ ?>
            <a href="http://www.buschfunk.com/kuenstler" title="zu den Künstlerprofilen">Künstler</a> +
            <a href="http://www.buschfunk.com/aktuell/konzerte" title="zu den Konzertterminen">Konzerte</a> +
            <a href="<?php echo $this->getUrl('') ?>" title="zur Startseite des Konsum">Konsum</a>
        </p>
        <p class="no-display"><a href="#main"><strong><?php echo $this->__('Skip to Main Content') ?> &raquo;</strong></a></p>
        <?php echo $this->getChildHtml('topSearch') ?>
    </div>
</div>
<?php echo $this->getChildHtml('topCart') ?>
