<?php

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @package    Mage_Debit
 * @copyright  Copyright (c) 2009 ITABS GbR - Rouven Alexander Rieker
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<p>
    <?php echo $this->getMethod()->getTitle() ?><br />
	
    <?php if ($this->getMethod()->getEmailSettings()): ?>
    	<?php echo $this->getMethod()->getEmailSettings(); ?>
    	<br /><br />
    <?php endif; ?>
    
    <?php if ($this->getMethod()->getCustomText()): ?>
        <?php echo $this->getMethod()->getCustomText() ?><br />
    <?php endif; ?>
</p>
