<?php
/**
 * BuschFunk Templates
 * Left > Orderable switcher
 *
 * @see Bufu_Catalog_Block_Orderable_Switch
 */

$session = Mage::getSingleton('checkout/session');
$active  = $session['archive'];
?>
<div class="orderable-switcher <?php if ($active) echo 'active'; else echo 'inactive'; ?>">
    <form name="show_not_orderable" id="show_not_orderable" method="post" action="<?php echo $this->getUrl('bcatalog/orderable/switch') ?>">
        <div id="show_not_orderable_status">
            <input type="checkbox" name="active" onchange="document.show_not_orderable.submit()" value="1" id="show_not_orderable_active"<?php if ($active) : ?> checked="checked"<?php endif; ?> />
            <label for="show_not_orderable_active"><?php echo $this->__('Show not orderable products') ?></label>
        </div>
    </form>
</div>