<?php
/**
 * BuschFunk Tenplates
 * Checkout > Cart > Crosssells
 */
?>
<?php
/**
 * Cart cross sell items template
 *
 * @see Mage_Checkout_Block_Cart_Crosssell
 */
?>
<?php if($this->getItemCount()): ?>
<div class="cms_divider"></div>
<div class="product-collateral cart-crosssell">
<div class="collateral-box">
    <div class="head">
        <h4><?php echo $this->__('Based on your selection, you may be interested in the following items:') ?></h4>
    </div>
    <ul class="generic-product-list">
    <?php foreach ($this->getItems() as $_item): ?>
        <li>
            <div class="product-box">
                <a href="<?php echo $_item->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(75); ?>" width="75" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image" /></a>
                <div class="product-shop">
                    <h5><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></h5>
                    <p class="artist-name"><?php echo Mage::getModel('catalog/product')->load($_item->getId())->getBufuArtist() ?></p>
                    <?php echo $this->getPriceHtml($_item, true) ?>
                    <?php if ($_item->isSaleable()) : ?>
                        <a title="<?php echo $this->__('Add to Cart') ?>" href="#" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')" class="gfx-button">
                            <span>
                                <span class="cart-put"><?php echo $this->__('Add to Cart') ?></span>
                            </span>
                        </a>
                    <?php else: ?>
                        <div class="out-of-stock"><?php echo $this->__('Out of stock!') ?></div>
                    <?php endif; ?>
                    <?php /*
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                    <small><a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="link-cart"><?php echo $this->__('Add to Wishlist') ?></a></small>
                    <?php endif; ?>
                    <?php if($_compareUrl=$this->getAddToCompareUrl($_item)): ?><br/>
                    <small><a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add to Compare') ?></a></small>
                    <?php endif; ?>
                    */ ?>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ul>
    <div class="clear"></div>
</div>
</div>
<?php endif; ?>
