<?php
/**
 * BuschFunk Tenplates
 * Checkout > Cart > No items in cart
 */
?>
<div class="page-head cart-noitems">
    <h3><?php echo $this->__('Shopping Cart is Empty') ?></h3>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<p><?php echo $this->__('You have no items in your shopping cart.') ?></p>
<p><?php echo $this->__('Please <a href="%s">continue shopping</a>.', $this->getContinueShoppingUrl()) ?></p>
