<?php
/**
 * BuschFunk Tenplates
 * Checkout > Cart
 */
?>
<?php
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>
<div class="page-head button-level cart-index">
    <h2><?php echo $this->__('My Shopping Cart') ?></h2>
    <?php if(!$this->hasError()): ?>
    <ul class="checkout-types">
        <?php echo $this->getChildHtml('top_methods') ?>
    </ul>
    <?php endif; ?>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form name="cartItemsForm" action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
<table cellspacing="0" border="0" id="shopping-cart-table" class="data-table box-table shopping-cart">
    <col width="40" />
    <col width="75" />
    <col />
<?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
    <col width="1" />
<?php endif ?>
<?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <col width="80" />
<?php endif; ?>
<?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <col width="80" />
<?php endif; ?>
    <col width="1" />
<?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <col width="80" />
<?php endif; ?>
<?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <col width="80" />
<?php endif; ?>


<?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
    <thead>
        <tr>
            <th class="header-blue last" colspan="100"><?php echo $this->__('Your cart contains the following products:') ?></th>
        </tr>
        <tr>
            <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Remove') ?></th>
            <th rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>
            <th rowspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Product Name') ?></th>
            <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
            <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Move to Wishlist') ?></th>
            <?php endif ?>
            <th class="a-center" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Unit Price') ?></th>
            <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Qty') ?></th>
            <th class="a-center last" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Subtotal') ?></th>
        </tr>
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
        <tr>
            <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
            <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
            <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
            <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
        </tr>
        <?php endif; ?>
    </thead>
    <tfoot>
        <tr>
            <td colspan="100" class="a-right">
                <?php if($this->getContinueShoppingUrl()): ?>
                    <a title="<?php echo $this->__('Continue Shopping') ?>" href="#" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')" class="gfx-button">
                        <span>
                            <span class="cart-put"><?php echo $this->__('Continue Shopping') ?></span>
                        </span>
                    </a>
                <?php endif; ?>
                <a title="<?php echo $this->__('Update Shopping Cart') ?>" href="#" onclick="cartItemsForm.submit();return false;" class="gfx-button right">
                    <span>
                        <span class="arrow-refresh"><?php echo $this->__('Update Shopping Cart') ?></span>
                    </span>
                </a>
            </td>
        </tr>
    </tfoot>
    <tbody>
    <?php foreach($this->getItems() as $_item): ?>
        <?php echo $this->getItemHtml($_item) ?>
    <?php endforeach ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('shopping-cart-table')</script>
<?php echo $this->getBlockHtml('formkey') ?>
</form>

<?php echo $this->getChildHtml('checkoutNotice'); ?>

<div class="shopping-cart-totals">
    <?php echo $this->getChildHtml('totals'); ?>
    <?php if(!$this->hasError()): ?>
    <ul class="checkout-types">
        <?php echo $this->getChildHtml('methods') ?>
    </ul>
    <?php endif; ?>
</div>
<div class="clear"></div>

<?php if (!$this->getIsVirtual()): ?>
<div class="shopping-cart-collaterals">
    <?php echo $this->getChildHtml('shipping'); ?>
</div>
<div class="clear"></div>
<?php endif; ?>

<?php echo $this->getChildHtml('crosssell') ?>
