<?php
/**
 * BuschFunk Tenplates
 * Checkout > Cart > Show totals
 */
?>
<?php
/**
 * Shopping cart totals template
 *
 * @see Mage_Checkout_Block_Cart_Totals
 */

// get zwischensummen incl. tax
$_zwischenSumme = 0.0;
foreach($this->getItems() as $item) {
    $_zwischenSumme += $this->helper('checkout')->getSubtotalInclTax($item);
}

$_totals = $this->getTotals();

// get versandkosten incl Tax
$_versand_incl = null;
if (isset($_totals['shipping'])) {
    $_versand_excl = $_totals['shipping']->getValue();
    $_versand_incl = $_versand_excl * 1.19;
}

// tax information
$tax_overall_amount = $_totals['tax']->getValue();
$tax_parts = $_totals['tax']->getFullInfo();

?>
<table cellspacing="0" id="shopping-cart-totals-table">
    <tfoot>
        <?php echo $this->renderTotals('footer'); ?>
    </tfoot>
    <tbody>
        <tr class="bufu-total">
            <td class="a-right"><?php echo $this->__('Subtotal (incl. Tax)') ?></td>
            <td><?php echo $this->helper('checkout')->formatPrice($_zwischenSumme) ?></td>
        </tr>
        <?php if (!is_null($_versand_incl)) : ?>
        <tr class="bufu-total">
            <td><?php echo $this->__('Shipping &amp; Processing') ?></td>
            <td><?php echo $this->helper('checkout')->formatPrice($this->helper('tax')->getShippingPrice($_versand_incl, true)) ?></td>
        </tr>
        <?php endif; ?>
        <?php $first = true; foreach($tax_parts as $tax) :?>
        <tr class="bufu-tax <?php if($first) { echo "first"; $first = false; } ?>">
            <td>enthaltene MwSt. <?php echo $tax['rates'][0]['percent'] ?>%</td>
            <td><?php echo $this->helper('checkout')->formatPrice($tax['amount']) ?></td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>