<?php
/**
 * BuschFunk Templates
 * Catalog > Featured Products List
 */
?>
<?php
/**
 * Product list template
 *
 * @see local > Mage_Catalog_Block_Product_List_Featured
 */
?>
<?php $_categories = $this->getFeaturedCategories(); ?>
<?php $i=0; foreach ($_categories as $_category): ?>

    <?php $_productCollection=$this->getFeaturedProductCollection($_category) ?>

    <?php $_collectionSize = $_productCollection->count();
        if ($_collectionSize > 0) :
    ?>
<div class="featured-list">
    <h3>Neuheiten <?php echo $this->getCategoryName($_category); ?></h3>
    <div class="listing-type-grid catalog-listing">
        <?php $_columnCount = $this->getColumnCount(); ?>
        <?php $i=0; foreach ($_productCollection as $_product): ?>
            <?php if($i++%$_columnCount==0): ?>
            <ol class="grid-row">
            <?php endif; ?>
                <li class="item <?php if($i%$_columnCount==0): ?>right<?php else: ?>left<?php endif; ?>">
                    <?php if ($_product->getBufuProductTeaser()) : ?>
                        <div class="teaser"><?php echo $_product->getBufuProductTeaser() ?></div>
                    <?php endif; ?>
                    <div class="product-image">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>">
                            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(120, 120); ?>" width="120" height="120" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" />
                        </a>
                        <?php if($_product->getRatingSummary()): ?>
                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        <?php endif; ?>
                    </div>
                    <div class="product-shop">
                        <h5><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h5>
                        <p class="author"><?php echo $_product->getBufuArtist() ?></p>
                        <?php if (strlen($_product->getAttributeText('bufu_medium'))>0) : ?>
                            <p><?php echo $this->htmlEscape($_product->getAttributeText('bufu_medium')) ?></p>
                        <?php endif; ?>
                        <?php /*
                        <p>
                            <a class="icon view" title="<?php echo $this->htmlEscape($_product->getName()) ?>" href="<?php echo $_product->getProductUrl() ?>">
                                <?php echo $this->__('View') ?>
                            </a>
                        </p>
                        */ ?>
                        <?php echo $this->getPriceHtml($_product, true, '', false) ?>
                        <?php if($_product->isSaleable()): ?>
                            <?php if ($_product->isPreorderable()) : ?>
                                <p class="preorder"><?php echo $this->__('Release on %s', $this->formatDate($_product->getBufuOrderableFrom())) ?></p>
                            <?php endif; ?>
                            <a class="gfx-button" title="Dieses Produkt in Ihren Warenkorb legen" href="<?php echo $this->getAddToCartUrl($_product) ?>">
                                <span>
                                    <span class="cart-put">
                                        <?php if ($_product->isPreorderable()) : ?>
                                            <?php echo $this->__('Preorder now') ?>
                                        <?php else : ?>
                                            <?php echo $this->__('Add to Cart') ?>
                                        <?php endif; ?>
                                    </span>
                                </span>
                            </a>
                        <?php else: ?>
                        <div class="out-of-stock"><?php echo $this->__('Out of stock!') ?></div>
                        <?php endif; ?>
                    </div>
                </li>
            <?php if($i%$_columnCount==0 || $i==$_collectionSize): ?>
            </ol>
            <?php endif; ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('.grid-row'), ['last', 'odd', 'even']);</script>
    </div>
</div>
    <?php endif; /* collection count */ ?>
<?php endforeach /* categories */ ?>