<?php
/**
 * BuschFunk Templates
 * Toolbar on Product lists
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */

$_defaultSortOrders = array(
    'bufu_release'  => 'desc',
    'relevance'     => 'desc',
    'bufu_artist'   => 'asc',
    'position'      => 'asc',
    'name'          => 'asc',
    'price'         => 'asc',
    'DEFAULT'       => 'asc'
);

?>
<?php if($this->getCollection()->getSize()): ?>
    <table class="pager" cellspacing="0">
        <tr>
            <?php if($this->getLastPageNum()>1): ?>
            <td class="pages">
                <strong><?php echo $this->__('Page:') ?></strong>
                <ol>
                <?php if (!$this->isFirstPage()): ?>
                    <li class="prevNext"><a href="<?php echo $this->getPreviousPageUrl() ?>"><img src="<?php echo $this->getSkinUrl('images/pager_arrow_left.gif') ?>" alt="<?php echo $this->__('Previous') ?>" /></a></li>
                <?php endif ?>
                <?php foreach ($this->getPages() as $_page): ?>
                    <?php if ($this->isPageCurrent($_page)): ?>
                        <li class="on"><span><?php echo $_page ?></span></li>
                    <?php else: ?>
                        <li><a href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a></li>
                    <?php endif ?>
                <?php endforeach;; ?>
                <?php if (!$this->isLastPage()): ?>
                    <li class="prevNext"><a href="<?php echo $this->getNextPageUrl() ?>"><img src="<?php echo $this->getSkinUrl('images/pager_arrow_right.gif') ?>" alt="<?php echo $this->__('Next') ?>" /></a></li>
                <?php endif ?>
                </ol>
            </td>
            <?php endif; ?>
            <td class="a-right">
                <?php echo $this->__('Show') ?> <select onchange="setLocation(this.value)">
                <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                    <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                        <?php echo $_limit ?>
                    </option>
                <?php endforeach; ?>
                </select> <?php echo $this->__('per page') ?>
            </td>
        </tr>
    </table>
    <?php if( $this->isExpanded() ): ?>
    <table class="view-by" cellspacing="0">
        <tr>
            <td>
                <?php if($this->getLastPageNum()>1): ?>
                    <?php echo $this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
                <?php else: ?>
                    <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
                <?php endif; ?>
            </td>
            <td class="sort-by">
                <?php echo $this->__('Sort by') ?> <select onchange="setLocation(this.value)">
                <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                    <?php var_dump($_key,$_order); ?>
                    <?php
                        if (array_key_exists($_key, $_defaultSortOrders))
                            $orderThis = $_defaultSortOrders[$_key];
                        else
                            $orderThis = $_defaultSortOrders['DEFAULT'];
                    ?>
                    <option value="<?php echo $this->getOrderUrl($_key, $orderThis) ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                        <?php echo $_order ?>
                    </option>
                <?php endforeach; ?>
                </select>
                <?php if($this->getCurrentDirection() == 'desc'): ?>
                    <a href="<?php echo $this->getOrderUrl(null, 'asc') ?>">Aufsteigend</a>
                <?php else: ?>
                    <a href="<?php echo $this->getOrderUrl(null, 'desc') ?>">Absteigend</a>
                <?php endif; ?>
            </td>
        </tr>
    </table>
    <?php endif; ?>
<?php endif ?>
