<?php
/**
 * BuschFunk Templates
 * > Catalog > Category View
 */
?>
<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>
<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imageUrl = $_category->getImageUrl()) {
        $_imgHtml = '<img src="'.$_imageUrl.'" alt="'.$this->htmlEscape($_category->getName()).'" width="475" />';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php if($this->isContentMode()): ?>
    <div class="category-head">
    <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
        <a href="<?php echo $this->getRssLink() ?>" class="link-feed right"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
    <?php endif; ?>
    <h2 class="cat-<?php echo $_category->getId(); ?>">
        <?php echo $_helper->categoryAttribute($_category, $this->htmlEscape($_category->getName()), 'name') ?>
    </h2>
    </div>
    <?php if($_imgHtml): ?>
        <p><?php echo $_imgHtml?></p>
    <?php endif; ?>
    <?php if($_description=$_category->getDescription()): ?>
        <p class="category-description"><?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?></p>
    <?php endif; ?>
    <?php echo $this->getCmsBlockHtml() ?>
<?php elseif($this->isMixedMode()): ?>
    <div class="category-head">
    <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
        <a href="<?php echo $this->getRssLink() ?>" class="link-feed right"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
    <?php endif; ?>
    <h2 class="cat-<?php echo $_category->getId(); ?>">
        <?php echo $_helper->categoryAttribute($_category, $this->htmlEscape($_category->getName()), 'name') ?>
    </h2>
    </div>
    <?php if($_imgHtml): ?>
        <p><?php echo $_imgHtml?></p>
    <?php endif; ?>
    <?php if($_description=$_category->getDescription()): ?>
        <p class="category-description"><?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?></p>
    <?php endif; ?>
<?php /*
    <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
        <a href="<?php echo $this->getRssLink() ?>" class="link-feed"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
    <?php endif; ?>
*/ ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <div class="category-head">
    <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
        <a href="<?php echo $this->getRssLink() ?>" class="link-feed right"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
    <?php endif; ?>
    <h2 class="cat-<?php echo $_category->getId(); ?>">
        <?php echo $_helper->categoryAttribute($_category, $this->htmlEscape($_category->getName()), 'name') ?>
    </h2>
    </div>
    <?php if($_imgHtml): ?>
        <p><?php echo $_imgHtml?></p>
    <?php endif; ?>
    <?php if($_description=$_category->getDescription()): ?>
        <p class="category-description"><?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?></p>
    <?php endif; ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>