<?php
/**
 * BuschFunk Templates
 * Catalog > Featured > Offers
 */

$_limit      = 6;                   # max number of products in collection
$_minimum    = 2;                   # min number of products in collection
$_imgMax     = 100;                 # max image dimension (w or h)
$_r = 217; $_g = 217; $_b = 217;    # RGB values of resized images' background color
?>
<div id="bufu_featured_offers">
    <h3><?php echo $this->__("Our monthly offers") ?></h3>
    <?php foreach($this->getProducts($_limit, $_minimum) as $_product) : ?>
        <div class="item">
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>">
                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->backgroundColor($_r,$_g,$_b)->resize($_imgMax, $_imgMax); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" />
            </a>
            <h4>
                <a href="<?php echo $_product->getProductUrl() ?>">
                    <?php echo $this->htmlEscape($_product->getBufuArtist()) ?>:
                    <strong><?php echo $this->htmlEscape($_product->getName()) ?></strong>
                    <?php if (strlen($_product->getAttributeText('bufu_medium'))>0) : ?>
                        (<?php echo $this->htmlEscape($_product->getAttributeText('bufu_medium')) ?>)
                    <?php endif; ?>
                </a>
            </h4>
            <?php echo $this->getPriceHtml($_product, false, '', false) ?>
        </div>
    <?php endforeach; ?>
</div>