version: '3.7'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  mysql:
    container_name: konsum_mysql
    image: bufu/konsum-mysql
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
      args:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - TZ=${TIMEZONE}
    volumes:
      - ${MYSQL_STORAGE_PATH_HOST}:${MYSQL_STORAGE_PATH_CONTAINER}
    ports:
      - "${MYSQL_HOST_PORT}:306"
    networks:
      - backend

  nginx:
    container_name: konsum_nginx
    image: bufu/konsum-nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER}
        - APP_GROUP=${APP_GROUP}
        - APP_GROUP_ID=${APP_GROUP_ID}
        - APP_USER=${APP_USER}
        - APP_USER_ID=${APP_USER_ID}
        - NGINX_ROOT=${NGINX_ROOT}
        - TZ=${TIMEZONE}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${APP_DATA_PATH_HOST_VAR}:${APP_DATA_PATH_CONTAINER_VAR}
      - ${APP_DATA_PATH_HOST_MEDIA}:${APP_DATA_PATH_CONTAINER_MEDIA}
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    networks:
      backend:
        aliases:
          - ${APP_HOST}

  php-fpm:
    container_name: konsum_phpfpm
    image: bufu/konsum-php-fpm
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
      args:
        - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER}
        - APP_GROUP=${APP_GROUP}
        - APP_GROUP_ID=${APP_GROUP_ID}
        - APP_USER=${APP_USER}
        - APP_USER_ID=${APP_USER_ID}
        - TARGET_PHP_VERSION=${PHP_VERSION}
        - TZ=${TIMEZONE}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${APP_DATA_PATH_HOST_VAR}:${APP_DATA_PATH_CONTAINER_VAR}
      - ${APP_DATA_PATH_HOST_MEDIA}:${APP_DATA_PATH_CONTAINER_MEDIA}
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: konsum_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
    networks:
      - backend

  workspace:
    container_name: konsum_workspace
    image: bufu/konsum-workspace
    build:
      context: .
      dockerfile: ./workspace/Dockerfile
      args:
        - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER}
        - APP_GROUP=${APP_GROUP}
        - APP_GROUP_ID=${APP_GROUP_ID}
        - APP_USER=${APP_USER}
        - APP_USER_ID=${APP_USER_ID}
        - TARGET_PHP_VERSION=${PHP_VERSION}
        - TZ=${TIMEZONE}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${APP_DATA_PATH_HOST_VAR}:${APP_DATA_PATH_CONTAINER_VAR}
      - ${APP_DATA_PATH_HOST_MEDIA}:${APP_DATA_PATH_CONTAINER_MEDIA}
    ports:
      - "${WORKSPACE_HOST_SSH_PORT}:22"
    networks:
      - backend
