<?php
/**
 * BuschFunk Templates
 * Catalog > Product > View
 */

/**
 * Product view template
 *
 * @see BuFu_Catalog_Block_Product_View
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();

    // determine whether product is of the attribute set "Ticket"
    $_isATicket = $this->helper('bufu_tickets')->isATicket($_product);
?>

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-info-box">
    <div class="product-essential">
    <form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>

        <div class="product-img-box">
            <?php if ($this->canEmailToFriend()): ?>
                <p>
                    <a title="<?php echo $this->__('Email to a Friend') ?>" onclick="setLocation('<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>')" class="gfx-button right">
                        <span>
                            <span class="email-go"><?php echo $this->__('Email to a Friend') ?></span>
                        </span>
                    </a>
                </p>
            <?php endif; ?>
            <?php echo $this->getChildHtml('media') ?>
        </div>

        <div class="product-shop">
            <?php if ($_product->getBufuProductTeaser()) : ?>
                <div class="teaser"><?php echo $_helper->productAttribute($_product, $this->htmlEscape($_product->getBufuProductTeaser()), 'bufu_product_teaser') ?></div>
            <?php endif; ?>
            <h3 class="product-name">
                <?php echo $_helper->productAttribute($_product, $this->htmlEscape($_product->getName()), 'name') ?>
            </h3>
            <?php if ($_product->getBufuArtist()): ?>
            <p class="artist">
                <?php echo $_helper->productAttribute($_product, $this->htmlEscape($_product->getBufuArtist()), 'bufu_artist') ?>
            </p>
            <?php endif; ?>

            <div class="product-shop-essentials">

                <?php if ($_product->getBufuMedium()): ?>
                <p class="item"><span>Medium:</span>
                    <?php echo $this->htmlEscape($this->getProduct()->getAttributeText('bufu_medium')) ?>
                </p>
                <?php endif; ?>

        <?php /*
                <?php if ($_product->getBufuLabel()): ?>
                <p class="item"><span>Label:</span>
                    <?php echo $_helper->productAttribute($_product, $this->htmlEscape($_product->getBufuLabel()), 'bufu_label') ?>
                </p>
                <?php endif; ?>
        */ ?>

                <?php if ($_product->getBufuRelease()): ?>
                <p class="item"><span>Erschienen:</span>
                    <?php echo substr($_helper->productAttribute($_product, $this->htmlEscape($_product->getBufuRelease()), 'bufu_release'),0,4) ?>
                </p>
                <?php endif; ?>
                <?php if ($_product->getSku()): ?>
                <p class="item"><span>Bestellnr.:</span>
                    <?php echo $_helper->productAttribute($_product, $this->htmlEscape($_product->getSku()), 'sku') ?>
                </p>
                <?php endif; ?>

                <?php if ($_product->getShortDescription()):?>
                    <div class="short-description"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                <?php endif;?>

                <?php echo $this->getChildHtml('alert_urls') ?>
                <?php echo $this->getChildHtml('product_type_data') ?>

                <fieldset class="no-display">
                  <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                  <input type="hidden" name="related_product" id="related-products-field" value="" />
                </fieldset>

                <?php echo $this->getTierPriceHtml() ?>

                <?php if (!$_isATicket && !$this->hasOptions()):?>
                    <?php if($_product->isSaleable()): ?>
                        <div class="add-to-holder">
                            <?php echo $this->getChildHtml('addtocart') ?>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
            </div>

            <?php echo $this->getChildHtml('other');?>

        </div>
        <div class="clear"></div>

        <?php if ($_isATicket) : ?>
            <?php echo $this->getChildHtml('bufu_tickets.view.options');?>
        <?php endif; ?>

        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
            <div class="clear"></div>
        <?php endif;?>

    </form>
    <script type="text/javascript">
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(){
                    if (this.validator.validate()) {
                            this.form.submit();
                    }
            }.bind(productAddToCartForm);
    </script>
    </div>

    <div class="product-collateral">
        <?php if ($_description = $this->getChildHtml('description')):?>
            <div class="collateral-box">
                <div class="head">
                    <h4><?php echo $this->__('Product Description') ?></h4>
                </div>
                <div class="product-specs">
                    <p class="description"><?php echo $_description ?></p>
                    <?php if ($_product->getBufuLinkToArtistProfile()): ?>
                    <p class="link-to-artist">
                        <a class="gfx-button" href="<?php echo $this->htmlEscape($_product->getBufuLinkToArtistProfile()) ?>" title="Zum Künstlerprofil von <?php echo $this->htmlEscape($_product->getBufuArtist()) ?>" target="_blank">
                            <span>
                                <span class="user-go">zum Künstlerportrait</span>
                            </span>
                        </a>
                        Weitere Informationen zu diesem Künstler<br />
                        finden Sie auch auf unserer Verlagshomepage.
                    </p>
                    <?php endif; ?>

                    <?php if ($_additional = $this->getChildHtml('additional')):?>
                        <?php echo $_additional ?>
                    <?php endif;?>

                    <?php if ($this->getTracklistHtml()) : ?>
                    <div class="trackList">
                        <h4>Titelliste</h4>
                        <?php echo $this->getTracklistHtml() ?>
                    </div>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif;?>

        <?php echo $this->getChildHtml('product_additional_data') ?>

        <?php echo $this->getChildHtml('upsell_products') ?>
    </div>
</div>
