<?php
/**
 * BuschFunk Templates
 * Checkout > Payment
 */
?>
<p class="hint">
    <?php echo $this->__('Please select a payment method for your order.') ?>
</p>

<script type="text/javascript">
var payment = new Payment('co-payment-form', '<?php echo $this->getUrl('checkout/onepage/savePayment') ?>');
</script>
<form action="" id="co-payment-form">
    <?php echo $this->getChildHtml('methods') ?>
    <div class="tool-tip" id="payment-tool-tip" style="display:none;">
        <div class="btn-close">
            <a href="#" id="payment-tool-tip-close"><img src="<?php echo $this->getSkinUrl('images/btn_window_close.gif') ?>" alt="<?php echo $this->__('Close') ?>" /></a>
        </div>
        <div class="block-content">
        <img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" />
        </div>
    </div>
</form>
<div class="button-set">
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <div id="payment-buttons-container">
        <a title="<?php echo $this->__('Back') ?>" href="#" onclick="checkout.back();return false" class="gfx-button left">
            <span>
                <span class="bullet-back"><?php echo $this->__('Back') ?></span>
            </span>
        </a>
        <a title="<?php echo $this->__('Continue') ?>" href="#" onclick="payment.save();return false" class="gfx-button right">
            <span>
                <span class="tick"><?php echo $this->__('Continue') ?></span>
            </span>
        </a>
    </div>
    <div id="payment-please-wait" style="display:none;" class="opc-please-wait">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="" /> &nbsp; <?php echo $this->__('Loading next step...') ?> &nbsp;
    </div>
</div>

<script type="text/javascript">
//<![CDATA[
    function toggleToolTip(event){
        if($('payment-tool-tip')){
            $('payment-tool-tip').setStyle({
                //left: (Event.pointerX(event)+100)+'px'
                top: (Event.pointerY(event)-515)+'px'
            })
            $('payment-tool-tip').toggle();
        }
        Event.stop(event);
    }
    if($('payment-tool-tip-close')){
        Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
    }

    $$('.cvv-what-is-this').each(function(element){
        Event.observe(element, 'click', toggleToolTip);
    });
//]]>
</script>
<script type="text/javascript">
//<![CDATA[
    payment.currentMethod = "<?php echo $this->getChild('methods')->getSelectedMethodCode() ?>";
//]]>
</script>
