<?php
/**
 * BuschFunk Templates
 * Checkout > Progress
 *
 * @see Mage_Checkout_Block_Onepage_Progress
 */
?>
<div id="one-page-checkout-progress-wrapper">
    <div class="box one-page-checkout-progress">
            <h3><?php echo $this->__('Your Checkout Progress') ?></h3>
        <ol>
        <?php if ($this->getCheckout()->getStepData('billing', 'is_show')): ?>
        <?php if ($this->getCheckout()->getStepData('billing', 'complete')): ?>
            <li>
                <h4 class="complete"><?php echo $this->__('Billing Address') ?> <span class="separator">|</span> <a href="#billing" onclick="checkout.accordion.openSection('opc-billing'); return false;" title="<?php echo $this->__('Edit') ?>"><img src="<?php echo $this->getSkinUrl('images/icons/arrow_refresh.png') ?>" alt="<?php echo $this->__('Edit') ?>" /></a></h4>
                <div class="content">
                    <address><?php echo $this->getBilling()->format('html') ?></address>
                </div>
            </li>
        <?php else: ?>
            <li>
                <h4><?php echo $this->__('Billing Address') ?></h4>
            </li>
        <?php endif; ?>
        <?php endif; ?>

        <?php if ($this->getCheckout()->getStepData('shipping', 'is_show')): ?>
        <?php if ($this->getCheckout()->getStepData('shipping', 'complete')): ?>
            <li>
                <h4 class="complete"><?php echo $this->__('Shipping Address') ?> <span class="separator">|</span> <a href="#payment" onclick="checkout.accordion.openSection('opc-shipping');return false;" title="<?php echo $this->__('Edit') ?>"><img src="<?php echo $this->getSkinUrl('images/icons/arrow_refresh.png') ?>" alt="<?php echo $this->__('Edit') ?>" /></a></h4>
                <div class="content">
                    <address><?php echo $this->getShipping()->format('html') ?></address>
                </div>
            </li>
        <?php else: ?>
            <li>
                <h4><?php echo $this->__('Shipping Address') ?></h4>
            </li>
        <?php endif; ?>
        <?php endif; ?>

        <?php if ($this->getCheckout()->getStepData('shipping_method', 'is_show')): ?>
        <?php if ($this->getCheckout()->getStepData('shipping_method', 'complete')): ?>
            <li>
                <h4 class="complete"><?php echo $this->__('Shipping Method') ?> <span class="separator">|</span> <a href="#shipping_method" onclick="checkout.accordion.openSection('opc-shipping_method'); return false;" title="<?php echo $this->__('Edit') ?>"><img src="<?php echo $this->getSkinUrl('images/icons/arrow_refresh.png') ?>" alt="<?php echo $this->__('Edit') ?>" /></a></h4>
                <div class="content">
                <?php if ($this->getShippingMethod()): ?>
                    <?php echo trim($this->getShippingDescription()," -"); ?>

                    <?php $_excl = $this->getShippingPriceExclTax(); ?>
                    <?php $_incl = $this->getShippingPriceInclTax(); ?>
                    <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
                        <?php echo $_incl; ?>
                    <?php else: ?>
                        <?php echo $_excl; ?>
                    <?php endif; ?>
                    <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                        (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                    <?php endif; ?>

                <?php else: ?>
                    <?php echo $this->__('Shipping method has not been selected yet') ?>
                <?php endif ?>
                </div>
            </li>
        <?php else: ?>
            <li>
                <h4><?php echo $this->__('Shipping Method') ?></h4>
            </li>
        <?php endif; ?>
        <?php endif; ?>

        <?php if ($this->getCheckout()->getStepData('payment', 'is_show')): ?>
        <?php if ($this->getCheckout()->getStepData('payment', 'complete')): ?>
            <li>
                <h4 class="complete"><?php echo $this->__('Payment Method') ?> <span class="separator">|</span> <a href="#payment" onclick="checkout.accordion.openSection('opc-payment');return false;" title="<?php echo $this->__('Edit') ?>"><img src="<?php echo $this->getSkinUrl('images/icons/arrow_refresh.png') ?>" alt="<?php echo $this->__('Edit') ?>" /></a></h4>
                <div class="content">
                    <?php echo $this->getPaymentHtml() ?>
                </div>
            </li>
        <?php else: ?>
            <li>
                <h4><?php echo $this->__('Payment Method') ?></h4>
            </li>
        <?php endif; ?>
        <?php endif; ?>
        </ol>
    </div>
</div>

<div class="opc-ssl-seal">
    <script type="text/javascript" src="https://seal.thawte.com/getthawteseal?host_name=konsum.buschfunk.com&amp;size=L&amp;lang=de"></script>
</div>