<?php
/**
 * BuschFunk Templates
 * Checkout > Shipping Methods
 */
?>
<p class="hint">
    <?php echo $this->__('Please select a shipping method for your order.') ?>
</p>

<form id="co-shipping-method-form" action="">
<div class="inner-box">
    <div class="default-box" id="checkout-shipping-method-load">
        <?php echo $this->getChildHtml('available') ?>
    </div>
</div>
<script type="text/javascript">
    var shippingMethod = new ShippingMethod('co-shipping-method-form', "<?php echo $this->getUrl('checkout/onepage/saveShippingMethod') ?>");

    var interval = window.setInterval("removeDoubleOption()", 100);
    function removeDoubleOption() {
        if (document.getElementById('bugfix_shipment-methods_dd_shipcalcmodule')) {
            // remove tablerates if shipCalc Module kicks in
            document.getElementById('bugfix_shipment-methods_dt_tablerate').style.display = "none";
            document.getElementById('bugfix_shipment-methods_dd_tablerate').style.display = "none";
        }
        //else {
        //    window.clearInterval(interval);
        //}
    }
</script>
<div id="onepage-checkout-shipping-method-additional-load">
<?php echo $this->getChildHtml('additional') ?>
</div>
</form>
<div class="inner-box">
    <div class="button-set no-border">
        <div id="shipping-method-buttons-container">
            <a title="<?php echo $this->__('Back') ?>" href="#" onclick="checkout.back();return false" class="gfx-button left">
                <span>
                    <span class="bullet-back"><?php echo $this->__('Back') ?></span>
                </span>
            </a>
            <a title="<?php echo $this->__('Continue') ?>" href="#" onclick="shippingMethod.save();return false" class="gfx-button right">
                <span>
                    <span class="tick"><?php echo $this->__('Continue') ?></span>
                </span>
            </a>
        </div>
        <div id="shipping-method-please-wait" style="display:none;" class="opc-please-wait">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="" /> &nbsp; <?php echo $this->__('Loading next step...') ?> &nbsp;
        </div>
    </div>
</div>
