<h2>Der Konsum ist vorübergehend nicht verfügbar</h2>
<p>Wir führen momentan Wartungsarbeiten durch. Das sollte aber nicht allzu lange dauern.<br />Bitte schauen Sie in einigen Minuten wieder vorbei. Vielen Dank!</p>
<div class="shopBtn right">
	<a title="zur Startseite" href="http://www.buschfunk.com" class="gfx-button">
		<span>
			<span class="cart-go">zur Verlagsseite</span>
		</span>
	</a>
</div>
<p>Herzliche Grüße,<br />Ihr BuschFunk-Kollektiv</p>
