<h2>Der Konsum ist vorübergehend nicht erreichbar</h2>
<p>Es werden momentan Wartungsarbeiten durchgeführt. <br />Bitte schauen Sie später wieder vorbei. Vielen Dank.</p>
<div class="shopBtn right">
	<a title="zur Startseite" href="http://www.buschfunk.com" class="gfx-button">
		<span>
			<span class="cart-go">zur Verlagsseite</span>
		</span>
	</a>
</div>
<p>Herzliche Grüße,<br />Ihr BuschFunk-Kollektiv</p>
