<?php
/**
 * BuschFunk Templates
 * Product > Review > Form
 */
?>
<div class="box-review-add">
    <div class="page-head">
        <h3><?php echo $this->__('Write Your Own Review') ?></h3>
    </div>
    <h4><?php echo $this->__("You're reviewing: %s", $this->htmlEscape($this->getProductInfo()->getName())) ?></h4>
    <form action="<?php echo $this->getAction() ?>" method="post" id="review-form" name="addReviewForm">
    <fieldset>
        <?php if( $this->getRatings() && $this->getRatings()->getSize()): ?>
        <div class="product-review-box">
        <strong><?php echo $this->__('How do you rate this product?') ?><span class="required">*</span></strong><br />
        <span id="input-message-box"></span>
        <table class="data-table" id="product-review-table" cellspacing="0">
            <thead>
                <tr>
                    <th>&nbsp;</th>
                    <th><?php echo $this->__('1 star') ?></th>
                    <th><?php echo $this->__('2 stars') ?></th>
                    <th><?php echo $this->__('3 stars') ?></th>
                    <th><?php echo $this->__('4 stars') ?></th>
                    <th class="last"><?php echo $this->__('5 stars') ?></th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($this->getRatings() as $_rating): ?>
                <tr>
                    <td class="label"><?php echo $_rating->getRatingCode() ?></td>
                <?php $_iterator = 1; ?>
                <?php foreach ($_rating->getOptions() as $_option): ?>
                    <!--<td <?php if($_iterator == 5): ?>class="last"<?php endif; ?> style="width:60px;"><input type="radio" <?php if($_iterator == 5): $_iterator=0; ?>class="validate-one-required-by-name"<?php endif; ?> name="ratings[<?php echo $_rating->getId() ?>]" id="<?php echo $_rating->getRatingCode() ?>_<?php echo $_option->getValue() ?>" value="<?php echo $_option->getId() ?>"/></td>-->
                    <td<?php if($_iterator == 5): ?> class="last"<?php endif; ?> style="width:60px;"><input type="radio" name="ratings[<?php echo $_rating->getId() ?>]" id="<?php echo $_rating->getRatingCode() ?>_<?php echo $_option->getValue() ?>" value="<?php echo $_option->getId() ?>" /></td>
                <?php $_iterator++ ?>
                <?php endforeach; ?>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <input type="hidden" name="validate_rating" class="validate-rating" value="" />
        <script type="text/javascript">decorateTable('product-review-table')</script>
        </div>
        <?php endif; ?>

        <?php // do not remove div - some problem whith validator in IE ?>
        <div>
        <label for="nickname_field"><?php echo $this->__('Nickname') ?><span class="required">*</span></label><br />
        <input class="input-text required-entry" name="nickname" id="nickname_field" style="width: 450px;" type="text" value="<?php echo $this->htmlEscape($data->getNickname()) ?>" />
        </div>

        <div>
        <label for="summary_field"><?php echo $this->__('Summary of Your Review') ?><span class="required">*</span></label><br />
        <input name="title" class="input-text  required-entry" id="summary_field" style="width: 450px;" type="text" value="<?php echo $this->htmlEscape($data->getTitle()) ?>" />
        </div>

        <div>
        <label for="review_field"><?php echo $this->__('Review') ?><span class="required">*</span></label><br />
        <textarea class="required-entry" name="detail" id="review_field" cols="53" rows="10" style="width: 450px;"><?php echo $this->htmlEscape($data->getDetail()) ?></textarea>
        </div>

        <div class="button-set">
            <a title="<?php echo $this->__('Submit Review') ?>" href="#" onclick="dataForm.submit();return false" class="gfx-button">
                <span>
                    <span class="comment-add"><?php echo $this->__('Submit Review') ?></span>
                </span>
            </a>
        </div>
    </fieldset>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('review-form');

        Validation.addAllThese(
        [
               ['validate-rating', '<?php echo $this->__('Please select one of each of the ratings above') ?>', function(v) {
                    var trs = $('product-review-table').getElementsBySelector('tr');
                    var inputs;
                    var error = 1;

                    for( var j=0; j < trs.length; j++ ) {
                        var tr = trs[j];
                        if( j > 0 ) {
                            inputs = tr.getElementsBySelector('input');

                            for( i in inputs ) {
                                if( inputs[i].checked == true ) {
                                    error = 0;
                                }
                            }

                            if( error == 1 ) {
                                return false;
                            } else {
                                error = 1;
                            }
                        }
                    }
                    return true;
                }]
        ]
        );
    //]]>
    </script>
</div>