<?php
/**
 * BuschFunk Templates
 * Catalog > PRoduct > Upsell
 */
?>
<?php if(count($this->getItemCollection()->getItems())): ?>
<div class="collateral-box up-sell">
    <div class="head"><h4><?php echo $this->__('You may also be interested in the following product(s)') ?></h4></div>
    <table cellspacing="0" class="generic-product-grid catalog-listing" id="upsell-product-table">
    <?php $this->resetItemsIterator() ?>
    <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
        <tr>
        <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
            <?php if($_link=$this->getIterableItem()): ?>
            <td>
                <p class="product-image"><a href="<?php echo $_link->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(125) ?>" width="125" height="125" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" /></a></p>
                <h5><a href="<?php echo $_link->getProductUrl() ?>"><?php echo $this->htmlEscape($_link->getName()) ?></a></h5>
                <p><?php echo $this->htmlEscape(Mage::getModel('catalog/product')->load($_link->getId())->getBufuArtist()); ?></p>
                <?php echo $this->getPriceHtml($_link, true, '', false) ?>
                <p>
                    <a class="icon view" title="<?php echo $this->htmlEscape($_link->getName()) ?>" href="<?php echo $_link->getProductUrl() ?>"><?php echo $this->__('View') ?></a>
                </p>
                <?php echo $this->getReviewsSummaryHtml($_link, null, false) ?>
                <?php if (!$_link->isSaleable()) : ?>
                    <div class="out-of-stock"><?php echo $this->__('Out of stock!') ?></div>
                <?php endif; ?>
            </td>
            <?php else: ?>
            <td class="empty-product">&nbsp;</td>
            <?php endif; ?>
        <?php endfor; ?>
        </tr>
    <?php endfor; ?>
    </table>
    <script type="text/javascript">decorateTable('upsell-product-table')</script>
</div>
<?php endif ?>
