<?php
/**
 * BuschFunk Templates
 * Catalog > View > Add-to-cart
 */
?>

<?php $_product = $this->getProduct() ?>

<?php if($_product->isSaleable()): ?>
    <fieldset class="add-to-cart-box">
        <legend><?php echo $this->__('Add Items to Cart') ?></legend>
        <?php if(!$_product->isGrouped()): ?>
        <span class="qty-box"><label for="qty"><?php echo $this->__('Qty') ?>:</label>
        <input name="qty" type="text" class="input-text qty" id="qty" maxlength="12" value="<?php echo ($this->getMinimalQty($_product)) > 1 ? $this->getMinimalQty($_product) : "1" ?>" /></span>
        <?php endif; ?>
        <a class="gfx-button" onclick="productAddToCartForm.submit()" title="Dieses Produkt in Ihren Warenkorb legen">
            <span>
                <span class="cart-put">
                    <?php if ($_product->isPreorderable()) : ?>
                        <?php echo $this->__('Preorder now') ?>
                    <?php else : ?>
                        <?php echo $this->__('Add to Cart') ?>
                    <?php endif; ?>
                </span>
            </span>
        </a>
    </fieldset>
<?php endif; ?>
