<?php
/**
 * BuschFunk Templates
 * Catalog > Product > View > Media
 */

/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */
?>

<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>


<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
<div class="product-img-box-inner">
<p class="product-image-zoom">
    <a href="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(500, 500) ?>" rel="lightbox">
    <?php
        $_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image')->backgroundColor(252,236,213)->resize(320, 300).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image')
    ?>
    </a>
</p>
</div>

<?php /*
<div class="image-zoom" id="track_outer">
    <img id="zoom_out" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_out.gif') ?>" alt="<?php echo $this->__('Zoom Out') ?>" class="btn-zoom-out" />
    <div id="track">
        <div id="handle"></div>
    </div>
    <img id="zoom_in" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_in.gif') ?>" alt="<?php echo $this->__('Zoom In') ?>" class="btn-zoom-in" />
</div>

<script type="text/javascript">
    Event.observe(window, 'load', function() {
        product_zoom = new Product.Zoom('image', 'track', 'handle', 'zoom_in', 'zoom_out', 'track_hint');
    });
</script>
*/ ?>

<?php else: ?>
<div class="product-img-box-inner">
    <p>
    <?php
        $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(290).'" alt="'.$this->htmlEscape($_product->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image')
    ?>
    </p>
</div>
<?php endif; ?>

<?php if (count($this->getGalleryImages()) > 1): ?>
<div class="more-views">
    <h4><?php echo $this->__('More Images') ?></h4>
    <ul>
    <?php foreach ($this->getGalleryImages() as $_image): ?>
        <li>
            <a href="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $_image->getFile())->resize(500, 500) ?>" rel="lightbox">
              <img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $_image->getFile())->resize(56); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
            </a>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
