<?php
/**
 * BuschFunk Templates
 * > Catalog Product List
 */
?>
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php $_productCollection=$this->getLoadedProductCollection() ?>
<?php if(!$_productCollection->count()): ?>
<div class="note-msg">
    <?php echo $this->__('There are no products matching the selection.') ?>
</div>
<?php else: ?>

<?php echo $this->getToolbarHtml() ?>
<?php // List mode ?>
<?php if($this->getMode()!='grid'): ?>
<div class="note-msg">
    <?php echo $this->__('List Display mode is not supported by this skin.') ?>
</div>
<?php $_iterator = 0; ?>
<div class="listing-type-list catalog-listing">
<?php foreach ($_productCollection as $_product): ?>
    <div class="listing-item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
        <?php // Product Image ?>
        <div class="product-image">
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getSmallImageLabel()) ?>">
                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135, 135); ?>" width="135" height="135" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" />
            </a>
        </div>

        <?php // Product description ?>
        <div class="product-shop">
            <h5><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName())?></a></h5>
            <?php if($_product->getRatingSummary()): ?>
            <?php echo $this->getReviewsSummaryHtml($_product) ?>
            <?php endif; ?>
            <?php echo $this->getPriceHtml($_product, true) ?>
            <?php if($_product->isSaleable()) : ?>
                <?php if (!Mage::helper('bufu_tickets')->isATicket($_product)) : ?>
                    <button class="form-button" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
                <?php endif; ?>
            <?php else: ?>
            <div class="out-of-stock"><?php echo $this->__('Out of stock') ?></div>
            <?php endif; ?>
            <div class="clear"></div>
            <div class="description">
                <?php echo nl2br($_product->getShortDescription()) ?>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><small><?php echo $this->__('Learn More') ?></small></a>
            </div>
            <p class="add-to">
                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-cart"><?php echo $this->__('Add to Wishlist') ?></a>
                <?php endif; ?>
                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                <span class="pipe">|</span>
                <a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add to Compare') ?></a>
                <?php endif; ?>
            </p>
        </div>
    </div>
<?php endforeach; ?>
</div>

<?php else: ?>

<?php // Grid Mode ?>
<div class="listing-type-grid catalog-listing">
<?php $_collectionSize = $_productCollection->count();

// check if we display search results
$isSearchResults = false;
if (false !== strstr(get_class($_productCollection), "Mage_CatalogSearch_"))
    $isSearchResults = true;

?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php
            // get full product class with all attributes for search entries
            if ($isSearchResults)
                $_product = Mage::getModel('catalog/product')->load($_product->getId());

            if($i++%$_columnCount==0):
        ?>
        <ol class="grid-row">
        <?php endif; ?>
            <li class="item <?php if($i%$_columnCount==0): ?>left<?php else: ?>right<?php endif; ?>">
                <?php if ($_product->getBufuProductTeaser()) : ?>
                    <div class="teaser"><?php echo $_product->getBufuProductTeaser() ?></div>
                <?php endif; ?>
                <div class="product-image">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(120, 120); ?>" width="120" height="120" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" />
                    </a>
                    <?php if($_product->getRatingSummary()): ?>
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?php endif; ?>
                </div>
                <div class="product-shop">
                    <?php if ($_product->isSaleable() && $_product->isPreorderable()) : ?>
                        <p class="preorder"><?php echo $this->__('Release on %s', $this->formatDate($_product->getBufuOrderableFrom())) ?></p>
                    <?php endif; ?>
                    <h5>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                            <?php echo $this->htmlEscape($_product->getName()) ?>
                        </a>
                    </h5>
                    <p class="author"><?php echo $_product->getBufuArtist() ?></p>
                    <?php if (strlen($_product->getAttributeText('bufu_medium'))>0) : ?>
                        <p><?php echo $this->htmlEscape($_product->getAttributeText('bufu_medium')) ?></p>
                    <?php endif; ?>

                    <?php /*
                    <p>
                        <a class="icon view" title="<?php echo $this->htmlEscape($_product->getName()) ?>" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View') ?></a>
                    </p>
                    */ ?>

                    <?php echo $this->getPriceHtml($_product, true, '', false) ?>
                    <?php if($_product->isSaleable()): ?>
                        <?php if (Mage::helper('bufu_tickets')->isATicket($_product)) : ?>

                        <a class="gfx-button" title="Termine für dieses Ticket ansehen" href="<?php echo $_product->getProductUrl() ?>#termine">
                            <span>
                                <span class="calendar">
                                    Termine ansehen
                                </span>
                            </span>
                        </a>

                        <?php else : ?>
                        <a class="gfx-button" title="Dieses Produkt in Ihren Warenkorb legen" href="<?php echo $this->getAddToCartUrl($_product) ?>">
                            <span>
                                <span class="cart-put">
                                <?php if ($_product->isPreorderable()) : ?>
                                    <?php echo $this->__('Preorder now') ?>
                                <?php else : ?>
                                    <?php echo $this->__('Add to Cart') ?>
                                <?php endif; ?>
                                </span>
                            </span>
                        </a>
                        <?php endif; ?>
                    <?php else: ?>
                    <div class="out-of-stock"><?php echo $this->__('Out of stock!') ?></div>
                    <?php endif; ?>
                </div>
            </li>
        <?php if($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ol>
        <?php endif; ?>
    <?php endforeach ?>
    <script type="text/javascript">decorateGeneric($$('.grid-row'), ['last', 'odd', 'even']);</script>
</div>
<?php endif; ?>
<?php echo $this->getToolbarHtml() ?>
<?php endif; ?>
