<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Phoenix
 * @package    Phoenix_CashOnDelivery
 * @copyright  Copyright (c) 2010 Phoenix Medien GmbH & Co. KG (http://www.phoenix-medien.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?>
    {{pdf_row_separator}}
<?php if ($this->getMethod()->getCustomText()): ?>
    <?php echo $this->htmlEscape($this->getMethod()->getCustomText()) ?><br />
<?php endif; ?>
    {{pdf_row_separator}}
<?php if ($this->getInfo()->getOrder()->getCodFee()): ?>
    <?php echo $this->__('Cash on Delivery fee')?>: <?php echo $this->getInfo()->getOrder()->formatPrice($this->getInfo()->getOrder()->getCodFee())?>

<?php endif; ?>