<?php
/**
 * BuschFunk Tenplates
 * Checkout > Cart > No items in cart
 */
?>
<div class="page-head cart-noitems">
    <h3><?php echo $this->__('Shopping Cart is Empty') ?></h3>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<p>
  <?php echo $this->__('You have no items in your shopping cart.') ?><br />
  <a href="<?php echo $this->getContinueShoppingUrl() ?>"><?php echo $this->__('Continue Shopping') ?></a>
</p>
