<?php
/**
 * BuschFunk Tenplates
 * Checkout > Cart > Show totals
 */
?>
<?php
/**
 * Shopping cart totals template
 *
 * @see Mage_Checkout_Block_Cart_Totals
 */

// get zwischensummen incl. tax
$_zwischenSumme = 0.0;
foreach($this->getItems() as $item) {
    $_zwischenSumme += $this->helper('checkout')->getSubtotalInclTax($item);
}

$_totals = $this->getTotals();

// get versandkosten incl Tax
$_versand_incl = 0;
if (isset($_totals['shipping'])) {
    $_versand_incl = $_totals['shipping']->getValue();
}

// tax information
$tax_parts = (array_key_exists('tax', $_totals)) ? $_totals['tax']->getFullInfo() : array();

?>
<table cellspacing="0" id="shopping-cart-totals-table">
    <tfoot>
        <?php echo $this->renderTotals('footer'); ?>
    </tfoot>
    <tbody>
        <tr class="bufu-total">
            <td class="a-right"><?php echo $this->__('Subtotal (incl. Tax)') ?></td>
            <td><?php echo $this->helper('checkout')->formatPrice($_zwischenSumme) ?></td>
        </tr>
        <?php $first = true; foreach($tax_parts as $tax) :?>
        <tr class="bufu-tax <?php if($first) { echo "first"; $first = false; } ?>">
            <td>enthaltene MwSt. <?php echo $tax['rates'][0]['percent'] ?>%</td>
            <td><?php echo $this->helper('checkout')->formatPrice($tax['amount']) ?></td>
        </tr>
        <?php endforeach ?>
		<?php if (0 !== $_versand_incl) : ?>
        <tr class="bufu-total">
            <td>zzgl. <?php echo $this->__('Shipping &amp; Processing') ?></td>
            <td><?php echo $this->helper('checkout')->formatPrice($this->helper('tax')->getShippingPrice($_versand_incl, true)) ?></td>
        </tr>
        <?php endif; ?>
		<tr class="bufu-total">
		<td class="a-right"><strong><?php echo $this->__('Grand Total') ?></strong></td>
		<td class="a-right"><strong><?php echo $this->helper('checkout')->formatPrice($_zwischenSumme + $_versand_incl) ?></strong></td>
	</tr>
    </tbody>
</table>