<?php
/**
 * BuschFunk Templates
 * > HTML Page 2-columns-left
 *
 *
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body <?php echo $this->getBodyClass()?'class="'.$this->getBodyClass().'"':'' ?>>
<div class="wrapper">
    <?php
    if (method_exists($this, 'isDisplayOutdatedBrowserNotice') && $this->isDisplayOutdatedBrowserNotice()) echo $this->getOutdatedBrowserNotice(); ?>

    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="header">
        <?php echo $this->getChildHtml('header') ?>
    </div>

    <div class="middle-container">
        <div class="middle col-2-left-layout">
            <?php echo $this->getChildHtml('breadcrumbs') ?>
            <div class="col-left side-col">
                <?php echo $this->getChildHtml('left') ?>&nbsp;
            </div>
            <div id="main" class="col-main">
                <?php echo $this->getChildHtml('global_messages') ?>
                <?php echo $this->getChildHtml('content') ?>
            </div>
        </div>
    </div>

    <div class="footer">
        <?php echo $this->getChildHtml('footer') ?>
    </div>

<?php echo $this->getChildHtml('before_body_end') ?>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>