<?php
/**
 * BuschFunk Templates
 * Admin > Order > View > name column of table
 */
?>
<?php
/**
 * @see Mage_Adminhtml_Block_Sales_Items_Column_Name
 */
?>

<?php if ($_item = $this->getItem()): ?>
    <h5 class="title"><?php echo $_item->getName() ?></h5>
    <div><strong><?php echo $this->helper('sales')->__('SKU') ?>:</strong> <?php echo implode('<br />', Mage::helper('catalog')->splitSku($this->getSku())); ?></div>

    <?php if (Mage::helper('bufu_tickets/admin')->hasTicketOptions($_item)):?>
    <!-- ticket options -->
        <div><strong>Titel:</strong> <?php echo Mage::helper('bufu_tickets/admin')->getTitleFromTicketProduct($_item) ?></div>
        <div><strong>Datum, Beginn:</strong> <?php echo Mage::helper('bufu_tickets/admin')->getDateFromTicketProduct($_item) ?>, <?php echo Mage::helper('bufu_tickets/admin')->getTimeFromTicketProduct($_item) ?></div>
        <div><strong>Ort:</strong> <?php echo Mage::helper('bufu_tickets/admin')->getLocationFromTicketProduct($_item) ?></div>
        <div><strong>Kategorie:</strong> <?php echo Mage::helper('bufu_tickets/admin')->getTypeFromTicketProduct($_item) ?></div>
    <!-- end ticket options -->
    <?php endif ?>

    <?php if ($this->getOrderOptions()): ?>
        <dl class="item-options">
        <?php foreach ($this->getOrderOptions() as $_option): ?>
            <dt><?php echo $_option['label'] ?></dt>
            <dd>
            <?php if (isset($_option['custom_view']) && $_option['custom_view']): ?>
                <?php echo $this->getCustomizedOptionValue($_option); ?>
            <?php else: ?>
                <?php echo Mage::helper('core/string')->truncate($_option['value'], 55, '', $_remainder);?>
                <?php if ($_remainder):?>
                    ... <span id="<?php echo $_id = 'id' . uniqid()?>"><?php echo $_remainder ?></span>
                    <script type="text/javascript">
                    $('<?php echo $_id ?>').hide();
                    $('<?php echo $_id ?>').up().observe('mouseover', function(){$('<?php echo $_id ?>').show();});
                    $('<?php echo $_id ?>').up().observe('mouseout',  function(){$('<?php echo $_id ?>').hide();});
                    </script>
                <?php endif;?>
            <?php endif;?>
            </dd>
        <?php endforeach; ?>
        </dl>
    <?php endif; ?>
    <?php echo $_item->getDescription() ?>
<?php endif; ?>