<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category  Symmetrics
 * @package   Symmetrics_TweaksGerman
 * @author    symmetrics - a CGI Group brand <info@symmetrics.de>
 * @author    Torsten Walluhn <torsten.walluhn@cgi.com>
 * @copyright 2012 symmetrics - a CGI Group brand
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link      http://www.symmetrics.de/
 */
?>
<?php
/**
 * @see Mage_Checkout_Block_Agreements
 */
?>

<?php if (!$this->getAgreements()) return; ?>
<form action="" id="checkout-agreements" onsubmit="return false;">
<ol class="checkout-agreements">
<?php foreach ($this->getAgreements() as $_agreement): ?>
    <li>
        <p class="agree2">
            <input type="checkbox" id="agreement-<?php echo $_agreement->getId()?>" name="agreement[<?php echo $_agreement->getId()?>]" value="1" title="<?php echo $this->htmlEscape($_agreement->getCheckboxText()) ?>" class="checkbox" /><label for="agreement-<?php echo $_agreement->getId()?>"><a href="#" onclick="window.open('<?php echo $this->getUrl('tweaksgerman/agreement/view', array('id' => $_agreement->getId())) ?>', '', 'width=600,height=600,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes').focus(); return false;"><?php echo $_agreement->getIsHtml() ? $_agreement->getCheckboxText() : $this->htmlEscape($_agreement->getCheckboxText()) ?></a></label>
        </p>
    </li>
<?php endforeach ?>
</ol>
</form>
