<?php
/**
 * BuschFunk Templates
 * Payment Info in Progress Bar -> Checkes
 */
?>
<p><?php echo $this->getMethod()->getTitle() ?>
<?php if($this->getInfo()->getAdditionalData()): ?>
    <?php if($this->getMailingAddress()): ?>
        <br />
        <span class="checkmo-mailing-address">
            <?php echo nl2br($this->htmlEscape($this->getMailingAddress())) ?>
        </span>
    <?php endif; ?>
<?php endif; ?>
</p>