<?php
/**
 * BuFu Templates
 * Catalogsearch > Mini Form on top of the page
 *
 * @see Bufu_CatalogSearch_Helper_Data
 */
?>
<form name="search_mini_form" id="search_mini_form" action="<?php echo $this->helper('catalogSearch')->getResultUrl() ?>" method="get">
    <fieldset>
        <legend><?php echo $this->__('Search Site') ?></legend>
        <div class="mini-search">
            <div class="content">
                <div class="search_categories">
                    <label for="search_categories">Suche in</label>
                    <select id="search_categories" name="<?php echo $this->helper('catalogSearch')->getSearchCategoryFieldname() ?>">
                    <?php
                        $_selected = $this->helper('catalogSearch')->getSelectedCategory();
                        foreach($this->helper('catalogSearch')->getSearchCategories() as $_category=>$_title) :
                    ?>
                        <option value="<?php echo $_category ?>"<?php if($_selected['value'] == $_category): ?> selected="selected"<?php endif; ?>><?php echo $this->__($_title) ?></option>
                    <?php endforeach; ?>
                    </select>
                </div>
                <div class="search_phrase">
                    <input id="search" type="text" class="input-text" name="<?php echo $this->helper('catalogSearch')->getQueryParamName() ?>" value="<?php echo $this->helper('catalogSearch')->getEscapedQueryText() ?>" />
                    <a href="#" onclick="return search_mini_form_submit()" title="<?php echo $this->__('Search') ?>" class="gfx-button right">
                        <span>
                            <span class="zoom-white">Suche</span>
                        </span>
                    </a>
                </div>

                <?php /*
                <p class="searchOption left">
                    <input type="checkbox" name="<?php echo $this->helper('catalogSearch')->getExcludeArtistParamName() ?>" id="searchoptions_artist" value="<?php echo $this->helper('catalogSearch')->getExcludeParamValueTrue(); ?>"
                        <?php if (!$this->helper('catalogSearch')->isExcludeArtistTrue()) : ?>checked="checked"<?php endif; ?>
                     />
                    <label for="searchoptions_artist">Künstler / Werke</label>
                </p>
                <p class="searchOption">
                    <input type="checkbox" name="<?php echo $this->helper('catalogSearch')->getExcludeTracksParamName() ?>" id="searchoptions_tracks" value="<?php echo $this->helper('catalogSearch')->getExcludeParamValueTrue(); ?>"
                        <?php if (!$this->helper('catalogSearch')->isExcludeTracksTrue()) : ?>checked="checked"<?php endif; ?>
                    />
                    <label for="searchoptions_tracks">Liedtitel / Tracklisten</label>
                </p>

                <input type="hidden" name="<?php echo $this->helper('catalogSearch')->getCheckForExcludesParamName(); ?>" value="<?php echo $this->helper('catalogSearch')->getExcludeParamValueTrue(); ?>" />

                */ ?>

                <div id="search_autocomplete" class="search-autocomplete"></div>
                <script type="text/javascript">
                //<![CDATA[
                    var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?php echo $this->__('Search entire store here...') ?>');
                    searchForm.initAutocomplete('<?php echo $this->helper('catalogSearch')->getSuggestUrl() ?>', 'search_autocomplete');

                    function search_mini_form_submit() {
                        if($('search').value == '<?php echo $this->__('Search entire store here...') ?>'
                            || $('search').value == ''
                        ) {
                            alert('<?php echo $this->__('Modify your search') ?>');
                        }
                        else {
                            document.search_mini_form.submit();
                        }
                        return false;
                    }
                //]]>
                </script>
            </div>
        </div>
    </fieldset>
</form>
