<?php
/**
 * BuschFunk Templates
 * Checkout > Review > Info
 */
?>
<table cellspacing="0" class="data-table" id="checkout-review-table">
    <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
    <thead>
        <tr>
            <th rowspan="<?php echo $rowspan ?>"><?php echo $this->__('Product Name') ?></th>
            <th class="a-center" colspan="<?php echo $colspan ?>" width="10%"><?php echo $this->__('Sku') ?></th>
            <th class="a-center" colspan="<?php echo $colspan ?>" width="10%"><?php echo $this->__('Price') ?></th>
            <th class="a-center" rowspan="<?php echo $rowspan ?>" width="5%"><?php echo $this->__('Qty') ?></th>
            <th class="a-center last" colspan="<?php echo $colspan ?>" width="10%"><?php echo $this->__('Subtotal') ?></th>
        </tr>
        <?php if ($this->helper('tax')->displayCartBothPrices()):?>
        <tr>
            <th class="a-right"><?php echo $this->__('Excl. Tax'); ?></th>
            <th class="a-right"><?php echo $this->__('Incl. Tax'); ?></th>
            <th class="a-right"><?php echo $this->__('Excl. Tax'); ?></th>
            <th class="a-right"><?php echo $this->__('Incl. Tax'); ?></th>
        </tr>
        <?php endif; ?>
    </thead>
    <?php echo $this->getChildHtml('totals'); ?>
    <tbody>
    <?php foreach($this->getItems() as $_item): ?>
        <?php echo $this->getItemHtml($_item)?>
    <?php endforeach ?>
    </tbody>
</table>
<script type="text/javascript">
//<![CDATA[
    decorateTable('checkout-review-table');
    truncateOptions();
//]]>
</script>
