<?php if ($this->hasBothPreorderedAndAvailableProducts()) : ?>
<ul class="messages" style="margin-top:1em !important; margin-bottom:1em !important">
  <li class="notice-msg">
      <strong>Teillieferung möglich</strong><br />
      Einige Produkte in Ihrer Bestellung können wir derzeit noch nicht liefern.<br />
      Wünschen Sie eine Teillieferung der verfügbaren Produkte? Dann vermerken Sie bitte "Teillieferung" im Bestellhinweis gleich unten.
      Es entstehen für Sie keine weiteren Kosten.
  </li>
</ul>
<?php endif; ?>
