<?php
/**
 * BuschFunk Templates
 * > Page Main Menu
 */
?>
<?php
/**
 * Top menu for store
 *
 * @see Mage_Catalog_Block_Navigation
 */
?>
<div class="header-nav-container">
    <div class="header-nav">
        <h4 class="no-display"><?php echo $this->__('Category Navigation:') ?></h4>
        <ul id="nav">
        <?php foreach ($this->getStoreCategories() as $_category): ?>
            <?php echo $this->drawItem($_category) ?>
        <?php endforeach ?>
            <li class="level0 nav-companyLink">
                <a href="http://verlag.buschfunk.com/">
                    <span>zur Verlagsseite</span>
                </a>
            </li>
        </ul>
    </div>
</div>
