<?php
/**
 * BuschFunk Templates
 * Catalog > Featured > Rotator
 */

$_limit      = 20;                  # number of products in rotator
$_shuffle    = true;                # random collection?
$_duration   = 4.0;                 # duration between two crossfades (sec)
$_transition = 2.0;                 # duration of the crossfade (sec)
$_r = 217; $_g = 217; $_b = 217;    # RGB values of resized images' background color

?>
<div id="bufu_featured_rotator">
    <?php $i = 1; foreach($this->getProducts($_limit, $_shuffle) as $_product) : ?>
        <div class="item" id="featured_rotator_<?php echo $i ?>"<?php if($i != 1) : ?> style="display:none"<?php endif; ?>>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>">
                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->backgroundColor($_r,$_g,$_b)->resize(150, 150); ?>" width="150" height="150" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" />
            </a>
            <h4>
                <?php echo $this->htmlEscape($_product->getBufuArtist()) ?>:
                <?php echo $this->htmlEscape($_product->getName()) ?>
                <?php if (strlen($_product->getAttributeText('bufu_medium'))>0) : ?>
                    (<?php echo $this->htmlEscape($_product->getAttributeText('bufu_medium')) ?>)
                <?php endif; ?>
            </h4>
        </div>
    <?php $i++; endforeach; ?>
</div>
<script type="text/javascript">
//<[CDATA[
    function showNext(step)
    {
        var nextStep = (step < <?php echo $_limit ?>) ? step+1 : 1;
        Effect.Fade("featured_rotator_"+step, {duration: <?php echo $_transition ?>});
        Effect.Appear("featured_rotator_"+nextStep, {duration: <?php echo $_transition ?>});
        window.setTimeout("showNext("+nextStep+")", <?php echo (int) ($_duration * 1000) ?>);
    }
    document.observe("dom:loaded", function() {
        var id = window.setTimeout("showNext(1)", <?php echo (int) ($_duration * 1000) ?>, 1);
    });
//]]>
</script>