<?php
/**
 * BuschFunk Templates
 * Send Mail to a friend
 */

/**
 * Send to friend form
 *
 * @see Mage_Sendfriend_Block_Index
 */
?>
<script type="text/javascript">
//<![CDATA[
    i=0;
    var recipCount  = 1;
    var maxRecip    = <?php echo $this->getMaxRecipients() ?>;
    function remove_recipient(i){
        $('recipients_name'+i).up(2).remove();
        recipCount--;
        if(recipCount<maxRecip && maxRecip != 0) {
            $('add_recipient_button').show();
            $('max_recipient_message').hide();
        }
        return false;
    }

    function add_recipient(){
        ul = $('recipients_options');
        var li_mail = Element.extend(document.createElement("LI"));
        li_mail.addClassName('addElement');
        li_mail.innerHTML = '<div class="right remove-btn"><a href="delete_email" onclick="remove_recipient('+i+');return false"><img src="<?php echo $this->getSkinUrl('images/list_remove_btn.gif') ?>" alt="<?php echo $this->__('Remove Email') ?>"/><\/a><\/div>'
        li_mail.innerHTML += '<div class="clear"><\/div>';
        li_mail.innerHTML += '<div class="left"><label for="recipients_name"><?php echo $this->__('Name:') ?> <span class="required">*<\/span><\/label><br /><div class="text-input"><input name="recipients[name][]" type="text" class="input-text required-entry" id="recipients_name'+i+'" /><\/div><\/div>';
        li_mail.innerHTML += '<div class="right"><label for="recipients_email"><?php echo $this->__('Email Address:') ?><span class="required">*<\/span><\/label><br /><div class="text-input"><input name="recipients[email][]" value="" title="<?php echo $this->__('Email Address') ?>" id="recipients_email'+i+'" type="text" class="input-text required-entry validate-email" /><\/div><\/div>';
        i++;
        recipCount++;
        if(recipCount>=maxRecip && maxRecip != 0) {
            $('add_recipient_button').hide();
            $('max_recipient_message').show();
        }

        ul.appendChild(li_mail);

        return false;
    }

    function populateMessageForm(setValue){
        elem = $('sender_message');
        if (elem.value == '') {
            elem.value = setValue;
        }
    }
//]]>
</script>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-head">
    <h2><?php echo $this->__('Email to a Friend') ?></h2>
</div>
<form name="product_sendtofriend_form" action="<?php echo $this->getUrl('*/*/sendmail', array('id'=>$this->getProductId(), 'cat_id'=>$this->getCategoryId())) ?>" method="post" id="product_sendtofriend_form">
<div class="box sendfriend-form">
    <div class="content">
        <div>
            <h4><?php echo $this->__('Sender:') ?></h4>
             <ul class="form-list" id="sender_options">
                   <li>
                        <div class="left">
                            <label for="sender_name"><?php echo $this->__('Name:') ?> <span class="required">*</span></label><br/>
                            <div class="text-input"><input name="sender[name]" value="<?php echo $this->htmlEscape($this->getUserName()) ?>" title="<?php echo $this->__('Name') ?>" id="sender_name" type="text" class="input-text required-entry" /></div>
                        </div>
                        <div class="right">
                           <label for="sender_email"><?php echo $this->__('Email:') ?> <span class="required">*</span></label><br/>
                           <div class="text-input"><input name="sender[email]" value="<?php echo $this->htmlEscape($this->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" id="sender_email" type="text" class="input-text required-entry validate-email" /></div>
                        </div>
                    </li>
                    <li>
                        <label for="sender_message"><?php echo $this->__('Message:') ?> <span class="required">*</span></label><br/>
                        <textarea name="sender[message]" class="input-text required-entry text-area" id="sender_message" cols="3" rows="3"><?php echo $this->htmlEscape($this->getFormData()->getData('sender/message'))?></textarea>
                    </li>

             </ul>
        </div>

        <div>
           <br />
           <h4><?php echo $this->__('Recipient:') ?></h4>
            <ul class="form-list" id="recipients_options">
                    <li class="addElement first">
                        <div class="left">
                            <label for="recipients_name"><?php echo $this->__('Name:') ?> <span class="required">*</span></label><br/>
                            <div class="text-input"><input name="recipients[name][]" type="text" class="input-text required-entry" id="recipients_name" /></div>
                        </div>
                        <div class="right">
                            <label for="recipients_email"><?php echo $this->__('Email Address:') ?> <span class="required">*</span></label><br/>
                            <div class="text-input"><input name="recipients[email][]" value="" title="<?php echo $this->__('Email Address') ?>" id="recipients_email" type="text" class="input-text required-entry validate-email" /></div>
                        </div>
                    </li>
            </ul>
       </div>
        <div class="clear"></div>

        <div class="button-set">
            <?php if (1 < $this->getMaxRecipients()): ?>
                <a id="add_recipient_button" title="<?php echo $this->__('Add Recipient') ?>" href="#" onclick="return add_recipient();" class="gfx-button">
                    <span>
                        <span class="user-add"><?php echo $this->__('Add Recipient') ?></span>
                    </span>
                </a>
                <div id="max_recipient_message" style="display:none">
                <?php if ($this->getMaxRecipients()): ?>
                  <?php echo $this->__('Maximum %d email addresses allowed.', $this->getMaxRecipients()) ?>
                <?php endif; ?>
                </div>
            <?php endif; ?>

            <a title="<?php echo $this->__('Send Email') ?>" href="#" onclick="productSendtofriendForm.submit()" class="gfx-button right">
                <span>
                    <span class="email-go"><?php echo $this->__('Send Email') ?></span>
                </span>
            </a>
            <?php if ($this->getProductId()) : ?>
            <a title="<?php echo $this->__('Cancel') ?>" href="#" onclick="setLocation('<?php echo Mage::getModel('catalog/product')->load($this->getProductId())->getProductUrl() ?>');return false" class="gfx-button right" style="margin-right:10px">
                <span>
                    <span class="cancel"><?php echo $this->__('Cancel') ?></span>
                </span>
            </a>
            <?php endif; ?>
        </div>
    </div>
</div>
</form>
<script type="text/javascript">
    var productSendtofriendForm = new VarienForm('product_sendtofriend_form');
    productSendtofriendForm.submit = function() {
        if(this.validator.validate()) {
            this.form.submit();
        }
    }.bind(productSendtofriendForm);

    <?php if ($this->getProductId()):
        $artist = Mage::getModel('catalog/product')->load($this->getProductId())->getBufuArtist();
        $name = Mage::getModel('catalog/product')->load($this->getProductId())->getName();
    ?>
    Event.observe( window, 'load', function() {
        populateMessageForm("Hallo,\nschau doch mal beim BuschFunk vorbei! Das hier könnte Dich interessieren:\n"
            <?php if ($artist && $name) : ?>
                + "\"<?php echo $name ?>\" von <?php echo $artist ?>\n"
            <?php elseif ($name) : ?>
                + "\"<?php echo $name ?>\"\n"
            <?php endif; ?>
            + "<?php echo Mage::getModel('catalog/product')->load($this->getProductId())->getProductUrl() ?>"
            + "\n\nViele Grüße!");
    });
    <?php endif; ?>
</script>
